version: "3"

services:

  app:
    build: .
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    build: db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"

  web:
    build: nginx
    volumes:
      - tmp-data:/myapp/tmp
    ports:
      - "80:80"
    depends_on:
      - app

  front:
    build: react
    volumes:
      - ./react/react-app:/usr/src/react-app
    ports:
      - "4000:3000"

volumes:
  public-data:
  tmp-data:
  db-data:
